language: java
install: 
- mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -P !build-extras -B
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
env:
  global:
  - GPG_DIR="`pwd`/cd"
  # GPG_KEYNAME
  - secure: niu6LYzcDfWP8A4vn0zhf1mmjp5Uf7lkxwvYEmo3rhhBMLcziPQV67vKdOlfJQA5Wg2p0TjAQEbVXWfVi+0Z5jWcc8bkMrQwH+MeBZeikKSQpLsFxJt1/UpeemPeafGAQDJ5eEyNKIc66xm6C7ro33pmFHR1EVMnh1QV8aja/uXMvszlqfZnbWn7T8vnRC+h0z/bYVPpgvyC1+4/o4pv6Y068sRSxeJw4VzOLOYy4wAnhmT/pivrAF9oDEhoP/w1EtXi5W8I0hicAurTNBGQrBSzLcFUNtWQlzN9U1byG45mTWXyi79U0KreyajCz48F3Rq27Bo9YBZNQO629HKMXC1+cjEKSX5Akpgmcp9KQNSkVENFLFUt3OWA4Ws7ovMdm225oKRaDZ1kb2xgLaxgIYbzafwqZB55BItfHKAqAaqodIArf/OD1AsbNX3LcoQLye4T2MhlnlduJ9Gk1jvhvF8Ga58AxRAi/qpDsCv2WQEdP+S6hsiB6/yyhq/ThzPamZvTYG16ZHPJq+CgStizTp79SK6gDBFEEPSQJK/KIfiNelQARFZBq9z7oeXXbBHk+8zh7aXgeFqFu1ht6k2jmCWRpWUciHLYMt/T3JbV7u20n6sOJM/5MdksOVV1spN7+bkffrnd7prkuOmoq/c8I0gXyn6XfF1n1IquCLD1YrY=
  # GPG_PASSPHRASE
  - secure: eyj/xL4rgtwlwy5wsuC5UNZTC67gBgV1/gzjc0X4YyiaSopUMsheP3o9jBuUdzgl+NUYABvQhGr2GTZQFi10Q4tOZcFmSEpjhkSvq/V27CzQ3ucK+tN4LkpuV3xmpr3BmfO1Fif0WS+ESHWe4zePcT3r9Qy48d20etZ9O0xvgsIRvapFXq1h4MH65AHZdfcDmHXL2NlFEHm9QlVssRKzxC3v61IFdPCZkAoyP6kCY8bPl5Y8q+IFMyxU00UuwipLdq3El5wvQewDHNIDrlaT9ZzVcdGMau3laNjg/BV279Sbq3aMeFKe3zEPosC0Qd4POlU8BgYiy6ZGMusgFmvrXm+lnw1yMvIkiHS+k15F9OyPHLIlTkcV6qNCp93mV5ozeFv0eGHhqdGgNFdw2zYNvMOqGEMcyX1UjR7KIhRGDFtVQUduCIKKfT+LJ9QAro8MXWOL6jtoOMfqmmR8MQ60MJX7wy+DGS9pxWrVNIzscYmK5+RBtW6CmiaWbUBvOVMUPFMpIjF42yOe4VBiChex8+nNvA68Pfk5o/ia868qlqHHFx9zSrbQDD/YvyTK8RC0ySL4OsuvL76s4HwGayMoIuB8OhiaHoErNJljcfled2oBGrqSxTgZnUJWiONVbP2sMVIwSFihBeVoSDblZoeO3c3620zsyXzm9xSq/Ol7H/U=
  # OSSRH_JIRA_USERNAME
  - secure: h7vD9Uw8MhvP6JPul5v1V8ziN7BtPA8YhxQ0WLUwLC7yYfv1Py9LsFxf9WhqqOBq2rQ+zgCTK3insnZjR+uNxjyBUYwYqUmg/LcPo+w2LK5ln484JGxpkXNybaH1TAqdHUcOJsvXGs8gf2UDZXQNAzgm/BueRv8P6d6UWpjcRO68+dCY7IONLw4n8mFeCsnRqB3+wxc2GUnWzq1bz4hBW9AC8FgFZZmYvZ5LGFy9QEQQAS7QLjO9EIh5u9woGoWJAhGXUX/dX2Ll2oCDwK9KQt8Osk0Qk5fiE/gx7Zt0j7fVTbNPXWMrzIwH8iTZD9g1p37yrDYfK8pZs9PhGLCTc8mzzpJfPVkkFHeDdZ/9mA/LNHqmii3Zb5ZmQ9+wR9BXFg30njRsJW8802P/zagf3T/l3Ok1zv17bDhWtdAqYSUdldeZWBkzOUoJbyUdsVdP8JkXaqBqt++y+bRr3Vfne25DaXGK3KFbxdlyU3r109dT7zb6yj5hcVBxtwGX0ATvKnpVgVsKAM79jmrbk0ceX37k8H8B1aEGSxfF6vW+Sl3a4VtPmt6sv7kbtmLpid3sBMqstf4DqIkhaGrcm1uxy0sBw8b3thToj2wC6jbsd567ifbMBBy6ANTbbvZIiCtlTM5X5pGmhw9+ByuYECdJdvMnZfudFhXRNNIZyVv06Sc=
  # OSSRH_JIRA_PASSWORD
  - secure: JdzZCMLvbfyoOJF9e49HBWvvbgi1LWcksUSe28xteS2m+NPDK+E2u3bGWoPwH9jg8IqEOUHhaglpFGOVQyEXXVgWaOgqBX+ofOOE3HBtcCOy8VEOSu2ktPtmj7Ln3Q9lJIFz6T/TkSOau8JEsI9RdKw0kp3H+yVaYDsZm70BW7K8L9BQrqUy78Vxtd5kNb//tIUMgYtCQ/is1EVAeY0XKm3jSqFpRNSObm9NynsF8dPXoPzFEP3s+tDNVNICNUFlbZuWoSqJjEbviXZICGcR/FfAtm5t9BjsDI4GuzRrlrwaQKHuioVqWdBktbhN7oHuRE29wDLoBs3uSnf+It1qgz96ho13j096/fTC2rrPosn+vW1i0Tl+z2y5VaCZtReg4vQhgaCn0n8/Au7gVE58RxgFCxwj0KkIUgNPuY9AX4evdR0x2yQmnPVpGH5zJAmOpo78/gIBXsjCmcC92GhiAhkv0Ig5cZFDNXcwxo9Cr13uWB8dcGpg5aHR9Ow8MLlxvqeCdcsasHfzZf0nwLHVDHEr3WG5I3xuX9KlpRlBXW/Xjc/yZ8XnESuoOAxaRvoDNU27hVmoM4T2VlT3uQ3WhW1qMaeIv1f6767SstWm0sMUJzawU+K6l5qsGpodhVS/o7Vr8jzVIrm3pmhdPPu787ThCROHn9gRnQfO8Im/k1I=
after_success:
- if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then 
  mvn sonar:sonar -Dsonar.login=${SONAR_TOKEN} -Dsonar.projectKey="camel-tooling-common" -Dsonar.projectName="Camel Tooling Common";
  ./cd/before-deploy.sh;
  ./cd/deploy.sh;
  fi
addons:
  sonarcloud:
    organization: "camel-tooling"
    branches:
      - master

